version: '3'

services:
  ortgdbserver:
    build:
      context: .
      dockerfile: Dockerfile.cuda
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    container_name: remote_debug
    ports:
      - "7776:22"     # ssh
      - "7777:7777"   # gdb
    volumes:
      - .:/home/ort_examples/
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=$DISPLAY
    entrypoint: "/usr/sbin/sshd -D"
    devices:
      - "/dev/dri:/dev/dri"
